version: "2"

linters:
  default: standard
  enable:
    - bodyclose
    - contextcheck
    - copyloopvar
    - errorlint
    - exhaustive
    - gocritic
    - misspell
    - nilerr
    - noctx
    - prealloc
    - unconvert
    - unparam
    - usestdlibvars
  settings:
    exhaustive:
      default-signifies-exhaustive: true
    misspell:
      locale: US

formatters:
  enable:
    - gofmt
    - goimports
