package main

import "testing"

func TestInspect(t *testing.T) {
	tests := []struct {
		name       string
		src        string
		violations int
	}{
		{
			name: "doc comments on exported api are allowed",
			src: `// Package x does things.
package x

// Registry holds tools.
type Registry struct {
	// Name identifies the registry.
	Name string
}

// Tool is a callable unit.
type Tool interface {
	// Run executes the tool.
	Run() error
}

// ErrMissing is returned when a tool is absent.
var ErrMissing = error(nil)

// Kinds of risk.
const (
	// RiskRead only reads data.
	RiskRead = "read"
)

// New builds a registry.
func New() *Registry { return &Registry{} }

// Len reports the size.
func (r *Registry) Len() int { return 0 }
`,
		},
		{
			name: "directives are allowed anywhere",
			src: `//go:build linux

package x

//go:noinline
func helper() {}
`,
		},
		{
			name: "generated files are skipped",
			src: `// Code generated by tool. DO NOT EDIT.

package x

// helper is unexported.
func helper() {}
`,
		},
		{
			name: "comments inside function bodies are forbidden",
			src: `package x

// Run runs.
func Run() {
	// explain the step
	_ = 1 // trailing note
}
`,
			violations: 2,
		},
		{
			name: "doc comments on unexported declarations are forbidden",
			src: `package x

// helper helps.
func helper() {}

// state is internal.
type state struct {
	// field is internal.
	field int
}

// Visible is exported.
type Visible struct {
	// hidden is unexported.
	hidden int
}

// Method on unexported type.
func (s state) Method() {}
`,
			violations: 5,
		},
		{
			name: "task markers are forbidden even in doc comments",
			src: `package x

// New builds a value. TODO: validate input.
func New() {}
`,
			violations: 1,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := inspect("x.go", tt.src)
			if err != nil {
				t.Fatalf("inspect: %v", err)
			}
			if len(got) != tt.violations {
				t.Fatalf("got %d violations, want %d: %v", len(got), tt.violations, got)
			}
		})
	}
}
